### ISSUE TITLE
Wand in vertical mode acts as if its in horizontal mode

### ISSUE THREAD

**Issue by RogueLogix** [Theta-Dev/ConstructionWand#28]
Placed wand in vertical mode, and it acted the same as in horizontal mode, seen with the infinity wand in AllTheMods 6.1.1.5
ToolTip is also incorrect here, stating that in vertical mode you can't build on the top/bottom faces, which is actually correct?

**Comment by Theta-Dev** [comment]
I've just tested it and I cant reproduce your issue.
North/South and East/West are supposed to build lines on the top face of a building (thus no building on side faces).
Horizontal and Vertical are supposed to build lines on the side of a building (thus no building on top/bottom faces).

Here are some images:
![2020-11-01_13 07 32](https://user-images.githubusercontent.com/19636565/97802464-deb93b80-1c43-11eb-920d-92ec3ba24561.png)
![2020-11-01_13 07 39](https://user-images.githubusercontent.com/19636565/97802466-dfea6880-1c43-11eb-9986-e7ff0636412a.png)
![2020-11-01_13 08 05](https://user-images.githubusercontent.com/19636565/97802469-e082ff00-1c43-11eb-8faa-cc0692126ff6.png)
![2020-11-01_13 08 13](https://user-images.githubusercontent.com/19636565/97802470-e11b9580-1c43-11eb-9bd5-a38d0ad4b38c.png)

FYI: if you file a bug report for a mod, always tell the developer the mod version you're using (you can get that by looking at the mod folder or in the forge mod menu) plus your Minecraft version. Because AllTheMods is currently the largest modpack including my mod, I know that it uses ConstructionWand 1.16.2-1.5, but I wont know that for smaller packs.

**Comment by RogueLogix** [comment]
Yea, sorry about that, i realized this was wrong but then got completely side tracked by issues with my own mod and never got around to correcting myself here. The actual issue is more that the mode names are a *bit* confusing, and there aren't a couple useful modes.

As a new player, I would expect horizontal mode, i would expect similar behaviour to none, but only allowing me to place on the sides of blocks. For vertical only on the top/bottom faces, but otherwise the same as none. So, i guess its more of a feature suggestion to add modes with those behaviours now.

**Comment by Theta-Dev** [comment]
Just went through it again - yes, I see that the mode descriptions might be misleading. I think I'll change them in the next update (I'll have to push one out anyway to add MC1.16.4 compatibility).

I wont add Top/Bottom or Side direction locks though. I had them in the first version, but I quickly realized that they were useless. Placing lines in North/South, East/West, Up/Down or Right/Left directions is very useful, for example for building walls inside your base. If you want to expand your skyblock island and dont want any misclicks - the Right/Left lock works for that, too.

Top/Bottom or side locks would only be useful for misclick prevention (and there is already the undo function for that). And unless your sneaking and holding left click to expand a platform you're standing on, I've never had any issues with so many misplacements that would make a direction lock worth it's time to set up.

**Comment by Theta-Dev** [comment]
Note: misleading direction lock descriptions fixed in Construction Wand V1.6
