### ISSUE TITLE
Wand doesn't work when crouching if crouch is bound to CTRL

### ISSUE THREAD

**Issue by bakkerthehacker** [Theta-Dev/ConstructionWand#32]
Rebinding sneak to CTRL stops the wand from working when sneaking.  Even after tweaking the very limited config options, I still cant get wand + sneak when using CTRL.

**Comment by Theta-Dev** [comment]
Yes, I'm aware of that. The Undo key is hardcoded to CTRL and the wand switches to undo mode when sneaking if that key is pressed.

I have tried to use keybinds but then you have an issue with the key conflict system, which prevents the use of already used keys.

I have an update in the making which allows the undo key to be changed in the config file. Not as convenient but still better than using keybinds, because then you would need to assign a "fresh" key to ConstructionWand.

**Comment by Theta-Dev** [comment]
Added option to change OPKEY in the config in CW2.0
https://github.com/Theta-Dev/ConstructionWand/releases/tag/1.16.2-2.0
