### ISSUE TITLE
[1.17.1] Client crash loop on crafting a diamond wand in an engineers decor metal workbench

### ISSUE THREAD

**Issue by ProsperCraft** [Theta-Dev/ConstructionWand#37]
One of my players on our dedicated server testing TownCrafft THREE alpha crafted a diamond wand and now can't log in.

I tried the same and I didn't have any problems.

https://gist.github.com/litjohn50/4403bb4a35e5dc1065dc5dc13daf7016
https://gist.github.com/litjohn50/96b64c63fb6fb615f02e8b89c2a76728

He crashes every time he logs in now.

Forge-1.17.1 - 37.0.59
constructionwand-1.17.1-2.2

**Comment by ProsperCraft** [comment]
With more testing and troubleshooting we have narrowed it down to an incompatibility with the scanables scanner.

**Comment by Theta-Dev** [comment]
I looked into this and it turned out that the code that handles item containers was not 1:1 compatible with Minecraft 1.17. That's why it crashed whenever you had an item container in your inventory.
So the scanners are not the problem, I had the same issue with toolbelts, too.

I have just released ConstructionWand 1.17.1-2.3, which fixes the issue.
