### ISSUE TITLE
[Suggestion/Issue] - Range not making sense

### ISSUE THREAD

**Issue by DemonSlayer112** [Theta-Dev/ConstructionWand#52]
Hello!
Im looking in my modpack to find a way to quarry huge areas.
I found a few ways but your wand shows to be the best way.

In createive the wand(infinity) shows as 1024 for construction mode, and 81 for destruction mode.
In creative weirdly destruction mode works for the 1024 range. And its BEAUTIFUL!
However, im truly sad to see its only the 81 in survival. And whats more? For Survival and Creative it has an rather odd range:
![image](https://user-images.githubusercontent.com/70122500/167231040-8e837861-bec5-414b-98a1-90e8f9d5fb6d.png)
45x45 + 29 blocks

The construction mode seems to cover roughly the same distance.

To make it even weirder(speaking of the extra bit north in the img, south in game) it moves from north/south.
And for the construction wand its still there but at a different size.

Other than the weird inperfect square, it would be fantasic if we could be able to config larger sizes for destruction wand(the best max would be 2304 blocks for a 3x3 chunk area)
I hope this gets some consideration, the other methods from other mods work, but there smaller and slower.

**Comment by Theta-Dev** [comment]
You can change the block limits for each wand type in the configuration file.

If you are using the infinity wand in creative mode it increases the bock limit to 2048 blocks by default (can be changed in the config, too).

The creative mode limit was added before the destruction core, that's why I didnt use a square number for that.

Allowing more than 81 blocks of instant destruction in survival mode would be too overpowered in my opinion. But you can crank the limit yourself if you like.

If you want to quarry larger areas in survival mode, I'd recommend the builder from RFTools with a voiding shape card.
And if you want to delete/set a large number of blocks in creative mode, WorldEdit is a much better option.
